name: Coverage

on:
  push:
    branches: [ master, coverage ]
    paths-ignore: '**.md'
  pull_request:
    branches: [ master, coverage ]
    paths-ignore: '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
      
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install -y build-essential cmake python3-pip pybind11-dev libeigen3-dev libfmt-dev libtbb-dev libomp-dev libpcl-dev libgtest-dev
          pip install -U setuptools pytest numpy scipy

      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DBUILD_BENCHMARKS=ON -DBUILD_WITH_TBB=ON -DBUILD_WITH_PCL=ON
          cmake --build . -j$(nproc)
          ctest -j$(nproc)
          cd ..
          python3 setup.py build && python3 setup.py install --user
          pytest src/example/basic_registration.py
